# Generated by Django 4.1.7 on 2023-03-19 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=6)),
                ('sheet', models.IntegerField()),
                ('task', models.IntegerField()),
                ('subtask', models.CharField(max_length=8)),
                ('assignment', models.CharField(blank=True, max_length=262144)),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True)),
                ('communicator', models.CharField(blank=True, max_length=64)),
                ('solution', models.CharField(blank=True, max_length=262144)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment')),
            ],
            options={
                'db_table': 'solution',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'testcase',
            },
        ),
        migrations.CreateModel(
            name='CompilesTestcase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assignments.testcase')),
                ('active', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'compiles_testcase',
            },
            bases=('assignments.testcase',),
        ),
        migrations.CreateModel(
            name='ContainsTestcase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assignments.testcase')),
                ('phrase', models.CharField(max_length=64)),
                ('times', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'db_table': 'contains_testcase',
            },
            bases=('assignments.testcase',),
        ),
        migrations.CreateModel(
            name='UnitTestcase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assignments.testcase')),
                ('file', models.FileField(blank=True, upload_to='db_files/')),
            ],
            options={
                'db_table': 'unit_testcase',
            },
            bases=('assignments.testcase',),
        ),
        migrations.CreateModel(
            name='Testresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True)),
                ('result', models.BooleanField(blank=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.solution')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.testcase')),
            ],
            options={
                'db_table': 'testresult',
            },
        ),
        migrations.AddField(
            model_name='solution',
            name='testresults',
            field=models.ManyToManyField(through='assignments.Testresult', to='assignments.testcase'),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('scope', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('tags', models.ManyToManyField(to='assignments.tag')),
            ],
            options={
                'db_table': 'classification',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='classification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignments.classification'),
        ),
    ]
