# Generated by Django 4.1.7 on 2023-03-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment',
            field=models.CharField(max_length=262144),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='classification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.classification'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subtask',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
