# Generated by Django 4.1.7 on 2023-03-20 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='classification',
        ),
        migrations.AddField(
            model_name='assignment',
            name='effort',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='scope',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tags',
            field=models.ManyToManyField(to='assignments.tag'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subtask',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
