# Generated by Django 4.1.7 on 2023-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
