# Generated by Django 4.1.7 on 2023-03-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_solution_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
            preserve_default=False,
        ),
    ]
