# Generated by Django 4.1.7 on 2023-03-20 17:28

from django.db import migrations, models
import django.db.models.deletion
import gui.communication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'llm',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(1, 'int'), (2, 'float'), (3, 'str')], default=gui.communication.models.PropertyType['float'])),
                ('mandatory', models.BooleanField()),
                ('language_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.languagemodel')),
            ],
            options={
                'db_table': 'llm_property',
            },
        ),
    ]
