# Generated by Django 4.1.7 on 2023-03-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_property_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_configuration',
            field=models.BooleanField(default=False),
        ),
    ]
