# Generated by Django 4.1.7 on 2023-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_solutionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionRequestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'solution_request_parameter',
            },
        ),
        migrations.AddField(
            model_name='solutionrequest',
            name='parameters',
            field=models.ManyToManyField(to='communication.solutionrequestparameter'),
        ),
    ]
