# Generated by Django 4.1.7 on 2023-03-22 16:34

from django.db import migrations, models
import gui.communication.models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_solutionrequestparameter_solutionrequest_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'not_ready'), (2, 'ready'), (3, 'running'), (4, 'completed')], default=gui.communication.models.SolutionRequestStatus['not_ready']),
        ),
    ]
