# Generated by Django 4.1.7 on 2023-03-26 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_solutionrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionrequest',
            name='repeats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
