# Generated by Django 4.1.7 on 2023-03-26 21:53

from django.db import migrations, models
import gui.communication.models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_solutionrequest_repeats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'not_ready'), (2, 'ready'), (3, 'running'), (4, 'completed'), (5, 'failed')], default=gui.communication.models.SolutionRequestStatus['not_ready']),
        ),
    ]
