# Generated by Django 4.2 on 2023-04-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_unittestcase_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='message',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
