# Base configuration information
version: 0.1

# Management Configuration
management:
  database:
    name: lmaa-local
    maxlength:
      assignment: 262144
      solution: 262144
    password: ""

# Communicator Configuration
communicator:
  openai-completion:
    apikey: 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

# Additional configuration
logging:
  level: INFO
  filename: lmaa-log.log
