# Base configuration information
version: 0.1

# Management Configuration
management:
  database:
    name: lmaa-local
    maxlength:
      assignment: 262144
      solution: 262144
    password: ""

# Communicator Configuration
communicator:
  openai-completion:
    apikey: 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

# Additional configuration
logging:
  level: INFO
  filename: lmaa-log.log
