# Generated by Django 4.1.7 on 2023-03-16 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=6)),
                ('sheet', models.IntegerField()),
                ('task', models.IntegerField()),
                ('subtask', models.CharField(max_length=8)),
                ('assignment', models.CharField(blank=True, max_length=262144)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effort', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('scope', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True)),
                ('communicator', models.CharField(blank=True, max_length=64)),
                ('solution', models.CharField(blank=True, max_length=262144)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Testresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True)),
                ('result', models.BooleanField(blank=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.solution')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='CompilesTestcase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.testcase')),
                ('active', models.BooleanField(blank=True)),
            ],
            bases=('gui.testcase',),
        ),
        migrations.CreateModel(
            name='ContainsTestcase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.testcase')),
                ('phrase', models.CharField(max_length=64)),
                ('times', models.IntegerField(blank=True, default=1)),
            ],
            bases=('gui.testcase',),
        ),
        migrations.CreateModel(
            name='UnitTestcase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gui.testcase')),
                ('file', models.FileField(blank=True, upload_to='db_files/')),
            ],
            bases=('gui.testcase',),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='solution',
            name='testresults',
            field=models.ManyToManyField(through='gui.Testresult', to='gui.testcase'),
        ),
        migrations.AddField(
            model_name='classification',
            name='tags',
            field=models.ManyToManyField(to='gui.tag'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gui.classification'),
        ),
    ]
