# Generated by Django 4.1.7 on 2023-03-16 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_assignment_classification_solution_tag_testcase_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table='assignment',
        ),
        migrations.AlterModelTable(
            name='classification',
            table='classification',
        ),
        migrations.AlterModelTable(
            name='compilestestcase',
            table='compiles_testcase',
        ),
        migrations.AlterModelTable(
            name='containstestcase',
            table='contains_testcase',
        ),
        migrations.AlterModelTable(
            name='solution',
            table='solution',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
        migrations.AlterModelTable(
            name='testcase',
            table='testcase',
        ),
        migrations.AlterModelTable(
            name='testresult',
            table='testresult',
        ),
        migrations.AlterModelTable(
            name='unittestcase',
            table='unit_testcase',
        ),
    ]
